### ISSUE TITLE
Failure to run the simulation_zone example on blender 4.0

### ISSUE THREAD

**Issue by tsatse** [carson-katri/geometry-script#41]
Hello,
I'm starting from the default cube on which I add a geometry node modifier,
I then type the following script (from the documentation) in the built-in editor : 

    from geometry_script import *
    
    @tree
    def test_sim(geometry: Geometry):
        @simulation_zone
        def my_sim(delta_time, geometry: Geometry, value: Float):
            return (False, geometry, value)
        return my_sim(geometry, 0.26).value

 I get the following error message : 

        Python: Traceback (most recent call last):
          File "\Text", line 4, in <module>
          File "C:\Users\tsatse\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\geometry-script-main\api\tree.py", line 149, in tree
            return build_tree(name)
          File "C:\Users\tsatse\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\geometry-script-main\api\tree.py", line 113, in build_tree
            outputs = builder(**builder_inputs)
          File "\Text", line 8, in test_sim
          File "C:\Users\tsatse\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\geometry-script-main\api\static\simulation.py", line 21, in wrapped
            simulation_in = State.current_node_tree.nodes.new(bpy.types.GeometryNodeSimulationInput.__name__)
        AttributeError: 'NoneType' object has no attribute 'nodes'

(my OS is windows 10)

**Comment by tsatse** [comment]
I tried to figure out in your code why the state's current node tree wasn't defined but I'm still trying to figure things out. I also tried to make it work with blender 3.6 and your commit that refactors simulation API to use "simulation_zone" but it didn't work either, with a similar error message, ie missing attribute 'nodes' in current_node_tree.

**Comment by rsaccon** [comment]
I cannot try the example (I am on Blender 3.6, on newer Blender my graphic card is not supported), but looking at the code, especially the signature of `my_sym`, it looks to me like you are calling it with wrong arguments, the `delta_time` is missing.

**Comment by tsatse** [comment]
yes, I tried adding that first argument but it didn't change anything. I looks like the simulation code tries to access the tree while it hasn't been built. I'm trying to understand all the code but I need to read about blender's api now

**Comment by alphadito** [comment]
Make sure the geometry script add-on folder is called 'geometry_script'. This will ensure that the correct state module is used instead of relying on `__init __.py` to [manually set](https://github.com/carson-katri/geometry-script/blob/6952ec507a6d0909d8ca1e49b1249c78b9c48cd4/__init__.py#L16) sys.modules which unfortunately doesn't work in all cases.

**Comment by tsatse** [comment]
Yesss ! It worked. Thank you so much
