### PR TITLE
Refactor simulation API to use `simulation_zone` decorator

### LINKED ISSUE #24: Simulation Input not create geometry socket
image

### PR DESCRIPTION
**Pull request by carson-katri**
Closes #24 

A new decorator called `@simulation_zone` will handle creating/pairing simulation input/output nodes together.

The simulation can contain any number of inputs. When called from the outside, the arguments passed are used as initial values to the simulation input.

Each zone should return a tuple with the same order as its arguments. These will be passed back into the zone on the next frame.

```python
from geometry_script import *

@tree
def test_sim(geometry: Geometry):
    @simulation_zone
    def my_sim(delta_time, geometry: Geometry, value: Float):
        return (geometry, value)
    return my_sim(geometry, 0.26).value
```

### CODE REVIEW

**Comment by jusu** [comment]
+1

Do I need a specific Blender version or am i doing something wrong? With the simulation example, I get:

`Python: Traceback (most recent call last):
  File "/Text", line 5, in <module>
  File "/Users/jusu/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-simulation-zone/api/tree.py", line 134, in tree
    return build_tree(name)
  File "/Users/jusu/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-simulation-zone/api/tree.py", line 98, in build_tree
    outputs = builder(**builder_inputs)
  File "/Text", line 9, in test_sim
  File "/Users/jusu/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-simulation-zone/api/static/simulation.py", line 19, in wrapped
    simulation_in = State.current_node_tree.nodes.new(bpy.types.GeometryNodeSimulationInput.__name__)
AttributeError: 'NoneType' object has no attribute 'nodes'
`


Most examples, like the "Repeat Grid" example, says:

`Python: Traceback (most recent call last):
  File "/Text", line 4, in <module>
  File "/Users/jusu/Library/Application Support/Blender/3.6/scripts/addons/geometry-script-simulation-zone/api/tree.py", line 98, in build_tree
    outputs = builder(**builder_inputs)
  File "/Text", line 8, in repeat_grid
TypeError: 'NoneType' object is not callable`

This is on Blender 3.6.5.
Thanks

**Comment by carson-katri** [comment]
@jusu The repeat grid example needs some changes depending on the Blender version. I think the one in the README does not work in 3.6 due to changes in the node arguments/outputs.
